# Generated by Django 3.2 on 2022-10-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.TextField()),
                ('company_name', models.TextField()),
                ('provide_salary', models.TextField()),
                ('work_area', models.TextField()),
                ('company_type', models.TextField()),
                ('job_welf', models.TextField()),
                ('company_size', models.TextField()),
                ('company_ind', models.TextField()),
                ('release_date', models.TextField()),
                ('attribute', models.TextField()),
                ('job_link', models.TextField()),
                ('company_link', models.TextField()),
            ],
            options={
                'db_table': 'jobs',
            },
        ),

    ]
