# Generated by Django 3.2 on 2022-10-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='users',
            name='major',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='users',
            name='project',
        ),
        migrations.RemoveField(
            model_name='users',
            name='project_content',
        ),
        migrations.RemoveField(
            model_name='users',
            name='project_duty',
        ),
        migrations.RemoveField(
            model_name='users',
            name='project_endtime',
        ),
        migrations.RemoveField(
            model_name='users',
            name='project_starttime',
        ),
        migrations.RemoveField(
            model_name='users',
            name='school',
        ),
        migrations.RemoveField(
            model_name='users',
            name='school_endtime',
        ),
        migrations.RemoveField(
            model_name='users',
            name='school_starttime',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_img',
        ),
        migrations.RemoveField(
            model_name='users',
            name='work',
        ),
        migrations.RemoveField(
            model_name='users',
            name='work_content',
        ),
        migrations.RemoveField(
            model_name='users',
            name='work_duty',
        ),
        migrations.RemoveField(
            model_name='users',
            name='work_endtime',
        ),
        migrations.RemoveField(
            model_name='users',
            name='work_starttime',
        ),
    ]
