# Generated by Django 3.2 on 2022-10-26 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_auto_20221026_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('school', models.CharField(max_length=20)),
                ('school_starttime', models.DateField()),
                ('school_endtime', models.DateField()),
                ('major', models.CharField(max_length=20)),
                ('project', models.CharField(max_length=20)),
                ('project_starttime', models.DateField()),
                ('project_endtime', models.DateField()),
                ('project_duty', models.CharField(max_length=20)),
                ('project_content', models.TextField()),
                ('work', models.CharField(max_length=20)),
                ('work_starttime', models.DateField()),
                ('work_endtime', models.DateField()),
                ('work_duty', models.CharField(max_length=20)),
                ('work_content', models.TextField()),
                ('evaluation', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobapp.users')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
