# Generated by Django 3.2 on 2022-10-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_auto_20221027_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('company_ind', models.TextField(verbose_name='公司介绍')),
            ],
            options={
                'db_table': 'company_info',
            },
        ),
    ]
