# Generated by Django 3.2 on 2022-10-30 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_cont',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobapp.companyinfo'),
        ),
    ]
